### ISSUE TITLE
Improve game points system?

### ISSUE THREAD

**Issue by vijayant123** [callofduty4x/CoD4x_Server#101]
Hello everyone!

My Thanks to the maintainers of CoD4. I noticed that CoD4X has a stable player-base. This is now a great time to improve its quality and make game-play more immersive.

The first on my list is the points system of CoD4X. Some features that I suggest:
1. Give out points to other/extra damages that are unrelated to the players (For eg. - heli kill/damage points, other ways that harm the enemy team)
2. More? Later on?

I would like all your suggestions for a better system (lets get the best from other/newer games). Also from the core developers I would like some pointers on where the related source files lie in the codebase and their suggestions.

Regards.
Vijayant Saini

**Comment by D4edalus** [comment]
many resources on modding can be found on our forums. however, gameplay mechanics are coded in GSC files, the cod4x server does not intend to change them in any way, but mostly replicates the original functionality and adds additional functionality for modders. 

everyone can of course write mods and plugins for the server, for example a new score system. some servers have done that already.

https://cod4x.me/forum/

**Comment by vijayant123** [comment]
But why not add some basic improvements to the score system (which can be toggled on/off) like the heli kill-points because many servers don't have experienced coders to manage plugins or code mods. I am talking about South-Asian  server hosters (India, Pakistan, Singapore) who like to play on vanilla CoD.

Also quoting the plugin interface for every new idea should not be the norm. We should also take our time to improve the legacy code in Cod4X so that it doesn't fall behind and gets more obsolete.

I am open to suggestions regarding other changes we can/need to make in the codebase (other features maybe?).

**Comment by vijayant123** [comment]
I am stressing heli kill-points because most players ignore enemy helicopters(it is not rewarding in any form). Those few who shoot at helis are also not very interested in doing so because it turns out to be just a waste of time. Giving out a pre-defined number of points to player on shooting helis would encourage everyone to shoot at them, than in the current situation where a helicopter's presence is only a threat to the top players of the team (which is highly irritating).   

I think these small features should be added to the core CoD4X instead and just being wrapped up in yet another mod.

**Comment by T-Maxxx** [comment]
Changing scripts is not a scope of CoD4X.

**Comment by D4edalus** [comment]
you are welcome to write such scripts and contribute to our modding section on the forums.
https://cod4x.me/forum/forum-6.html
there are already some servers featuring what you said

**Comment by vijayant123** [comment]
Sorry for this late reply.

I have one more question.

Why was fixing the helicopter related scripts (helicopter spawn logic and kill logic (for eg. the fact that it targets top players first)) under the scope of CoD4X but fixing the obsolete, buggy and shitty points system not?

All I am saying is that its time to update it and the changes I would like to make would be as un-opinionated as possible if you guys give the go ahead. These changes would provide a better interface to points and ranks and allow modders to write better mods and scripts.

Another feature I thought was to increase Profile levels/ranks from 55 to some other number and make it take a longer time to level up. Right now in a scoreboard all the players are at level 55 which is not a correct and genuine representation of their skills (and noobness).

**Comment by D4edalus** [comment]
helicopter spawn and kill logic is and was not tackled by the cod4x project. or did i miss something?
gameplay specifics like adjusting helicopter strenght is already possible in the core game. helicopter logic, for example, is fully defined in _helicopter.gsc. 
every server owner who wants to change the helicopters behaviour can easily edit named file or use associated variables to customize behaviour. 

we do not intend to change the games original concepts, however server owners are free to change the servers behaviour to their interests with plugins / scripts. 

if you want to change the ranking system i *think* you can change that rather easily with a mod (codjumper, deathrun, and others do that). many players also like the original system, we dont indend to create a new ranking system at this point. if you want to customize ranks on your server you have the possibility to grant prestige icons to players via scripts. 
personally i agree that the old ranking system IS rather pointless today, and i am also experimenting with new ways of ranking and keeping games balanced on my own servers.

if you have more concrete expectations or ideas please formulate them on the forums. 
we will not introduce a new ranking system as it would be forced on all cod4x server owners and players. gameplay changes will probably always be optional.

**Comment by IceNinjaman** [comment]
Well I would like to discuss this topic a bit further.
First of all it is right that the current development team does only create core engine patches. Scripts are at the moment setup by every server-admin on its own and many of the servers offer a different gameplay due to custom scripts. In this context any level/rank systems make no sense and show really nothing about the players skill/experience/gametime.
However I could imagine to have a different core game experience by improving assets, adding maps, adding interesting features and improving game logic. In such a scenario we could extend the level system as well as you have asked before and store players levels on a global server. However the current development staff is not going to do that. At least 2 of us don't understand very much about modding in the classic sense. Also we better spend our time with engine tweaks as we know that better. If there is someone who is willing to do it we can discuss it further. In this kind of system we have to make sure that scripts are untouchable by server-admins obviously as they want to make use of the levelsystem.
This levelsystem however would still not reflect someones skill. If you want a skill based ranking system you have to do something like in CS:GO. Having matchmaking and servers just for the purpose to run this matches. Here it would be needed again someone who want to provide actually around 30 servers with 10 or 12 slots without having a benefit of them. Someone who creates menus for the matchmaking thing. Create/Customize the gamelogic to run the "competitive" matches (CS:GO is super popular example how it could work). For doing the engine logic doing the matchmaking stuff I'd be willing to do that.

**Comment by T-Maxxx** [comment]
Few months without any updates. I think discussion can be closed and all devs are focused on engine.
