### ISSUE TITLE
main_shared from fs_homepath

### ISSUE THREAD

**Issue by pvolkv** [callofduty4x/CoD4x_Server#134]
Just a suggestion. It would be convenient if we could tune **main_shared** scripts independently from main iwd files. I mean if server could look for **main_shared** in **fs_homepath** folder, but use the same IWD's from **fs_basepath**. Now I have to copy all 3GB of IWD's if I want different scripts working.
Is it possible?
Thanks!

**Comment by T-Maxxx** [comment]
Should be added as "home_shared" :)

**Comment by D4edalus** [comment]
yeah its behaving weird .. 
files in fs_homepath/main_shared  do not override files in fs_basepath/main_shared. imho files in homepath should override files in basepath. however, i dont know if that would break other things.

you could try with gsx file extension. you could also try to use devdirs instead of main_shared (set fs_usedevdir 1)

**Comment by T-Maxxx** [comment]
![image](https://cloud.githubusercontent.com/assets/7836454/23123194/80ff5cf2-f778-11e6-8cdb-1fe3752fde6b.png)
Yep, "main_shared" must be added for fs_homepath and not for fs_basepath. I don't know how it will work for UNIX so a little help here? I heard fs_homepath and fs_basepath are different for unix by default.

**Comment by D4edalus** [comment]
afaik the homepath on linux points to ~/.callofduty ( or ~/.callofduty4 ? ) 
idk why, and i have never looked into it. on my servers i always set fs_homepath . to avoid any troubles
i guess thats the difference you heared about.

in general i had the same issue as you mentioned above on linux. basegame/main_shared is loaded instead of homepath/main_shared.

**Comment by iznogod** [comment]
Why not create a master main folder template and soft-link from there? No need to copy any files.

**Comment by D4edalus** [comment]
symlinking everything together works of course. when i started to run multiple servers that was the obvious solution to me since i didnt know how all those fs_<paths> work together.

using the filesystem variables enables you to achieve the same with less configuration. new server folders are less cluttered with links. idk about windows and symlinks ( mklink would work probably ) but i think fs_ variables are the cleaner solution
