### ISSUE TITLE
building with makefiles doesnt increase build number

### ISSUE THREAD

**Issue by D4edalus** [callofduty4x/CoD4x_Server#172]
building with makefiles doesnt increase build number within src/version_build.h

i also noticed if i just change the number in version_build.h and rebuild with the new makefile it still contains the old version number. i had to do "make clean" to get it working. isnt that the whole point of the new makefile to not be required to fully rebuild? @T-Maxxx

**Comment by T-Maxxx** [comment]
Yea, that's a problem with all this header files.

**Comment by D4edalus** [comment]
what does that mean, it just doesnt recognize changes in headerfiles at all?

**Comment by T-Maxxx** [comment]
Yes. Only files with source code.
For example, I have a rule `%.o: %.c %.h` - `make` must process `%.c` and `%.h` rule and only then process `%.o: ...` rule. The problem is we don't have to build header files at all. But they're included in source files. Still, source file keeps unchanged (in our case of version - static line "#include bla-bla-bla"). That's why `make` won't build `%.c` rule if header file changed.

**Comment by T-Maxxx** [comment]
@D4edalus Check "versioning" branch.

**Comment by D4edalus** [comment]
https://github.com/callofduty4x/CoD4x_Server/commits/versioning
i havent looked at it yet, but if its advancing the version number now just merge it i guess. 

fyi i have continued a little on the new makefile stuff in your old feature branch, i think im going to merge that soon. 
https://github.com/callofduty4x/CoD4x_Server/commits/makefile2

**Comment by T-Maxxx** [comment]
Incremental build means build only changed files. I made version file rebuilt each time but to increase build number you have to use external program/script. From the other hand, you can try to add script of this kind to makefile.
