### ISSUE TITLE
REFACTOR Plugin System ASAP

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#182]
Current one REALLY SUCKS. Sorry, guys, I'm a bit pissed off. If you wouldn't mind, I want to change directory layout for plugin handler/plugins itself a bit to make it at least compileable without any problems I got shot with. This is not my first plugin and each time I have something weird.

**Comment by D4edalus** [comment]
much rage? "Current one REALLY SUCKS" does seem to be a convincing reason for an overhaul.

**Comment by D4edalus** [comment]
ah i see, because its broken already by your recent changes =P

why all this arithmetic in the PluginEvents enum? kinda horrible to read. why not just do a clean split between runtime and management methods on all levels? why did you split them in the first place? 

looking at the error i found that OnExitLevel is correctly called at the server start. after loading the new level it is crashing for me on calling OnUserInfoChanged, however OnGotAuthInfo is called within the plugin.

**Comment by T-Maxxx** [comment]
My bad, sorry.
For example, with almost any plugin there provided "q_<something>.h/.c" file which contains both declarations and definitions for few string util functions. Why not just export them from binary then?
Same for struct declarations - they're just outdated in comparsion to server code.
When I'm developing plugin, I'm writing "Scr_GetInt(0)" and because it's not exist in plugin, I have to use "Plugin_Scr_GetInt(0)" each time. Repeat it 15 times for 15 different script functions for 2-3 plugins and it become a bit annoying because it's easier to reference server code than find declaration  inside some phander headers. (already refactored that ;P )
Again about structures. Of course, I can include any header file with required structure right from /src/ directory but almost all of them contains declarations for functions. So I'm writing plugin, codecompleter highlights one of this function, I'm using it - BANG - ~you're dead~ definition not found all over code. Sad to hear that but no other way than reference phander guts again.
I hope you get my point.
What I have done so far:
* Got rid of pluginexports.asm. Now it's plugin_api.h/.c;
* All exported functions now behaves like pointers (Plugin_Scr_GetInt() -> Scr_GetInt(), one-line call or return);
* All required (for now) are moved from headers to <header>_types.h file so phandler includes no function declarations, only types.

About that plugin events stuff.
I prefer C++ way where all functions (+functors) have their own type. But I see, you want to execute plugin events for all plugins in the same way: pass unique ID, pass parameters and we're good. Thats seems pretty for me. All the math is just for loops so we can add more plugin events without editing loops ranges in code. I did not split it into 2 enums because...hmm... Both are events, maybe? Besides, the lesser management enums we have - the easier to support it. I have grouped it into management and runtime because for runtime there is a storage like int[runtime_funcs_count] and for management there unique fields with its own names. 
I'll take a look, didn't really tested it.

**Comment by D4edalus** [comment]
the code duplication was bad i agree. 

`When I'm developing plugin, I'm writing "Scr_GetInt(0)" and because it's not exist in plugin, I have to use "Plugin_Scr_GetInt(0)" each time. Repeat it 15 times for 15 different script functions for 2-3 plugins and it become a bit annoying because it's easier to reference server code than find declaration inside some phander headers.`
imho thats just your personal taste and usage of codecompletion tools. all the Plugin_* functions make it very explicit what is usable from withing the plugins, and looking it up in one file wasnt hard at all before. 

as long as existing plugins dont need to be recompiled the changes are fine to me. otherwise tons of servers will break during the next update. 

a branch would have been nice instead of breaking master ..

**Comment by T-Maxxx** [comment]
Done. Master had been reset and my changes are on refactoring branch.

**Comment by D4edalus** [comment]
thats good, thanks
