### ISSUE TITLE
Plugin handler v4 against v3.1

### ISSUE THREAD

**Issue by T-Maxxx** [callofduty4x/CoD4x_Server#254]
What has been changed so major version has been increased? Is it possible to keep major and increase minor instead?

**Comment by D4edalus** [comment]
i was wondering about that too. my plugins worked fine so far with the new version.

**Comment by T-Maxxx** [comment]
Ppl started complaining about plugins.

**Comment by IceNinjaman** [comment]
All offsets for all members in struct client_s are different. That why this was needed.

**Comment by wkuzma** [comment]
is there going to be a release of the plugins like simplebanlist.dll and b3hide.dll for us windows users?
the reason I bring this here is because the plugins in xbase_00.iwd included with the 17.6 windows server download on the main page - do not load. 
^1Error: Failed to load the plugin c:\cod4-wargames\plugin.simplebanlist.tmp!
^1Error: This plugin might not be compatible with this server

**Comment by D4edalus** [comment]
plugins have already been updated on the website a while ago
