### ISSUE TITLE
bobmax problem forcing dvar to 1 every round

### ISSUE THREAD

**Issue by CroatianWarriors** [callofduty4x/CoD4x_Server#255]
Fix bobmax 0/1 to stop force 1

**Comment by D4edalus** [comment]
most useful bugreport 5/7.

anyways, discussed in https://cod4x.me/index.php?/forums/topic/2818-bg_bobmax-0
variables got re-initialized after round change + cheat protected variables have been reset in the process.

fixed in https://github.com/callofduty4x/CoD4x_Server/commit/59b656bfecfe49caaf83cc31615027f87b837501
