### ISSUE TITLE
Add Github releases for v17.7.2+ versions

### ISSUE THREAD

**Issue by qdm12** [callofduty4x/CoD4x_Server#299]
I would ideally need some Github releases to track versions for building your program from source, thanks! At least, one for v17.7.8 would be nice.

**Comment by T-Maxxx** [comment]
I'm glad to see it too.

**Comment by damdo** [comment]
Yes, what @qdm12 suggested would be very useful! @T-Maxxx 
Currently the latest release is from @D4edalus and it is `v17.7.2`.

It would be great to have them tagged/released every time a `.zip` package is created for the _Download_ section of the website, when https://cod4x.me/downloads/cod4x_server-linux.zip and https://cod4x.me/downloads/cod4x_server-windows.zip are created and uploaded.

Is there already a process in place for the tagging/release?

I've put together a small list of commits in which the `SYS_COMMONVERSION` constant in https://github.com/callofduty4x/CoD4x_Server/blob/master/src/version/version.c was edited, which might be useful to this purpose:
https://github.com/callofduty4x/CoD4x_Server/commit/d581a888fda586b383209600ae6737969b33334c 18.2
https://github.com/callofduty4x/CoD4x_Server/commit/9e0fbecc7dd75447e3037f7e6ba6612b73ad63a0 18.0
https://github.com/callofduty4x/CoD4x_Server/commit/4e32a1f447d5b1f861dfbdbc43c81e6495d7a8e4 17.10
https://github.com/callofduty4x/CoD4x_Server/commit/11b620d0074de717329faed7c956968eef10eb92 17.9
https://github.com/callofduty4x/CoD4x_Server/commit/abf470469e8ff24d65cc5d28ab804b8621d43c9e 17.8

A trivial release process that could be introduced could involve adding a `tag` target in the Makefile that is responsible for tagging the commit and that could be invoked whenever the version in https://github.com/callofduty4x/CoD4x_Server/blob/master/src/version/version.c is bumped, this could also be tied into a `release` target that could be responsible for invoking the `tag` target and could further package the artefacts.

What do you think?
Thank you.

**Comment by IceNinjaman** [comment]
@damdo sounds like a great idea, but unfortunately I don't really know how to do it.

**Comment by damdo** [comment]
Great to hear!
So it's should be quite straightforward.

I saw that this repository is already set up with Travis CI and Appveyor. And it turns out Appveyor is already configured to trigger a GitHub release (a deployment in Appveyor jargon) if a `git tag` is pushed. 
If you are interested in how that works you can find more info here:
- https://www.appveyor.com/docs/deployment/#deploy-on-tag-github-and-gitlab-only
- https://www.appveyor.com/docs/deployment/github/

You can see that from the config here:
https://github.com/callofduty4x/CoD4x_Server/blob/dc4ceb3ca51641aa40ae4b5c16d252549b91da8b/appveyor.yml#L62-L72

If the config is correctly set up you should be able to generate a new release every time you push a git tag.

So that said I would now do two things:
1) I would tag the commits I mentioned in the post above with the corresponding versions
   Doing this should be as simple as:
   ```bash
   # tag the various commits with their corresponding version change
   # this is just a suggestion, please double check with the other members of the team
   # that these versions correspond to the same content of the zip releases
   # you did on the https://cod4x.me/ website
   # then move to the repository and tag the commits
   git tag -a 17.8 abf4704
   git tag -a 17.9 11b620d
   git tag -a 17.10 4e32a1f
   git tag -a 18.0 9e0fbec
   git tag -a 18.2 d581a88
   # push the tags (this should trigger the CI system to create a release)
   git push origin --tags
   ```
2) I would come up with a somewhat defined process for releasing things, so that all new version changes that you define in https://github.com/callofduty4x/CoD4x_Server/blob/master/src/version/version.c will then correspond to a `git tag` of that same commit in which you change the `version.c` file, which will then correspond to a GitHub release generated by the CI system you use, and which might be then also packaged as an archive file that you can upload to the https://cod4x.me/ website under the _Download_ section.
One option for doing that is to:
_a)_ do all the necessary changes you want to include in a new release
_b)_ write the new version you want to assing to the changes to `SYS_COMMONVERSION` under `src/version/version.c`
_c)_ commit/PR/merge to `master`
_d)_ call `make release` to tag the latest commit with the version you specified in the `version.c` file, push it to GitHub and wait for Appveyor to create a new release
_e)_ optionally define some logic to create a `.zip` archive (with the release version in the filename) that you'll then put on the _Download_ section of the website.

Here below is an example on how to extrapolate the version from the `version.c` file and use it to tag the commit and release it:
```
@# put this at the top of the Makefile with the other variables
VERSION=$(shell grep '\#define SYS_COMMONVERSION' src/version/version.c | cut -d' ' -f3)

@# define this new target for tagging and releasing
.PHONY: release
release:
    @echo "Are you sure you want to create a GitHub Release? [y/N] " && read ans && [ $${ans:-N} = y ]
    git tag -a $(VERSION)
    git push origin --tags
    @# (optionally put your zip archiving logic here below)
```

These are just suggestions and by no means are verified to be correct. Please be sure to check the correctness and the feasibility of it with your team.

I hope you find this useful :)

**Comment by IceNinjaman** [comment]
Thanks a lot @damdo for your suggestions. I have most of it now implemented. Still I need to get a workaround that I can use the release target under Windows later. I am just bad with makefiles.
Well I am kinda on my own regarding the team. I did not check the commits you wrote me because it is not possible to verify which commit was also released without huge effort.

**Comment by damdo** [comment]
Thanks for doing it @IceNinjaman, good job! 👏 
@qdm12 FYI, the GitHub releases (tags) are now [there](https://github.com/callofduty4x/CoD4x_Server/releases) also for `v17.7.2`+ versions, together with the new release workflow.

**Comment by qdm12** [comment]
Nice, thanks everyone 💯

I updated my [repo](https://github.com/qdm12/cod4-docker/blob/master/Dockerfile#L32) to use these a few days ago already 👍

Can we close the issue now guys?

**Comment by damdo** [comment]
Great! I think so, yes.
