### ISSUE TITLE
New feature?

### ISSUE THREAD

**Issue by K-Faktor** [callofduty4x/CoD4x_Server#325]
what did this update bring?
https://github.com/callofduty4x/CoD4x_Server/tree/c82c54b906bbdc984198e1d6c5d5d9b1f6f66a87

**Comment by T-Maxxx** [comment]
Probably, preparations for verification of master servers using certs.

**Comment by K-Faktor** [comment]
Благодарю за ответ. Давно не видно было тебя. Пока не буду рисковать ставить на живой сервер, хотя мои игроки до сихпор испытывают проблемы с iwd файлами хотя и игра чистая.

**Comment by IceNinjaman** [comment]
There are no more preparations. Everything is done. It is far less exciting as you think. Doing HTTPS with properly updated root certificates and being able to do it before the filesystem is started up was the whole intention. It is needed to download the globalconfig.cfg from Github at an early stage. Some more variables are configurable now. This is required since I am aware I will lose control over the currently used domain by the start of next February.

**Comment by K-Faktor** [comment]
Thanks IceNinjaman. Then you can release an update for everyone
