### ISSUE TITLE
Is the new website cod4x.ovh?

### ISSUE THREAD

**Issue by UsmanTariq2** [callofduty4x/CoD4x_Server#355]
Cant find it

**Comment by Sampo2910** [comment]
Site is down right now.

**Comment by IceNinjaman** [comment]
Yes cod4x.ovh, renewing of cod4x.me turned to be impossible due to Google account lock-outs.

**Comment by KeinNerd** [comment]
Nice to see the Forum up again. But i cant register with Discord -> Error "Invalid OAuth2 redirect_uri". Hope you can fix it soon ;)

**Comment by UsmanTariq2** [comment]
> Google account lock-outs

Dude, u realize how many people will be confused now.

**Comment by danielmotaleite** [comment]
So several problems here:
-losing the domain opens the door to someone injecting malware via the cod4x update
-new users can't play because the installer is v20.1 and can't update to v20.5
-the current site don't allow register of new users in the forum (can't test the login)
-google still reports cod4x.me as the main site

So please publish a update ASAP, to fix the update server to the new domain. people will have to manually update, but after that all should work again. social network would warn people about the need to manual update

Update the code and pages still with cod4x.me to the new domain: https://github.com/search?q=org%3Acallofduty4x+cod4x.me
Finally, reconfigure the forum and login so it works again :)

Anyway, a updated release is needed, i have new players unable to play due the lack of update server

**Comment by Sampo2910** [comment]
In your link chnage .me to .ovh Job Done..

The solution is here!

https://cod4x.ovh/index.php?/forums/topic/6347-update-server/&tab=comments#comment-25565

**Comment by Sampo2910** [comment]
> So several problems here: -losing the domain opens the door to someone injecting malware via the cod4x update -new users can't play because the installer is v20.1 and can't update to v20.5 -the current site don't allow register of new users in the forum (can't test the login) -google still reports cod4x.me as the main site
> 
> So please publish a update ASAP, to fix the update server to the new domain. people will have to manually update, but after that all should work again. social network would warn people about the need to manual update
> 
> Update the code and pages still with cod4x.me to the new domain: https://github.com/search?q=org%3Acallofduty4x+cod4x.me Finally, reconfigure the forum and login so it works again :)
> 
> Anyway, a updated release is needed, i have new players unable to play due the lack of update server

Domain is not lost, its changed.

Easy Fix for 20.1 to 20.5 (takes 30 seconds) Answer is [Here](https://cod4x.ovh/index.php?/forums/topic/6351-cannot-update-from-v201/&tab=comments#comment-25572)


The forum and login does work.

**Comment by IceNinjaman** [comment]
> 1: -losing the domain opens the door to someone injecting malware via the cod4x update
> 2: -new users can't play because the installer is v20.1 and can't update to v20.5
> 3: -the current site don't allow register of new users in the forum (can't test the login)
> 4: -google still reports cod4x.me as the main site
> 
> 5: So please publish a update ASAP, to fix the update server to the new domain. people will have to manually update, but after that all should work again. social network would warn people about the need to manual update
> 

1: Don't worry, I have hashing and public key cryptography in use to mitigate this kind of dangers.
2: New update (works possible only manually) is in the progress.
3: You should be able to join via Discord login
4: I don't know how I have any influence on it.
5: Possible a manual update will be necessary since I have overseen something unfortunately. Maybe I can abuse the not yet used anti cheat loader for doing the updating somehow. But that would require a server update.

**Comment by IceNinjaman** [comment]
I have released on the website a version called 20.6.

**Comment by danielmotaleite** [comment]
Thanks for all the info and the update @IceNinjaman  and @Sampo2910 
the google, all we can do is submit the sitemaps, to speed up the change...  but slowly google will switch over, specially when the old domain do not respond anymore.

I think this can be closed now
