### ISSUE TITLE
Logfile logging Steamid or nothhing

### ISSUE THREAD

**Issue by IceNinjaman** [callofduty4x/CoD4x_Server#56]
Just putting here what I did pick up some days ago:
The server logs into logfiles the Steam id but not the player id. For players not having a Steam id its always [I:0:0].
Missing details which logfile. I assume games_mp.log
If someone has details please add.

**Comment by Kingwolf123** [comment]
Yes, the log-file doesnot switch between playerID and SteamID if for example the SteamID cannot be found [null value : [I:0:0]. Instead of switching to playerID in the LogFiles, the server keeps parsing the Steam ID which would be a null value and thus totally non-useful .

**Comment by IceNinjaman** [comment]
Can you please add which logfile it is?

**Comment by Kingwolf123** [comment]
Im talking about games_mp.log

**Comment by Kingwolf123** [comment]
An Example of the games_mp.log as generated by Version 16.1. (3 September 2016)
```
 17:53 Q;[U:1:156574713];2;KingWolf         'when steam is active
 18:16 `J;[I:0:0];2;KingWolf                           ' when we turn off steam, server doesnot switch to logging player ID
```

**Comment by IceNinjaman** [comment]
Fixed. Will only log playerid now as 64bit string

**Comment by Kingwolf123** [comment]
Only Logging PlayerID would not be a smart move if in the future B3 is to be supported for Cod4X again. The Server Needs to switch between PlayerID and SteamID. If SteamID is present, it is preferable to log SteamID instead of PlayerID. So if this feature can be implemented, it may be possible to get support for B3 in future,
